- name: Deploy to K8s Cluster
  hosts: bastion
  become: yes
  become_user: root
  vars_files:
    - ./vars.yaml
  tasks:
  - name: access key
    shell: |
      aws configure set aws_access_key_id {{access_key}}
  - name: secret key
    shell: |
      aws configure set aws_secret_access_key {{secret_key}}
  - name: token
    shell: |
      aws configure set aws_session_token {{aws_session_token}}
  - name: connect to the cluster
    shell: |
      aws eks update-kubeconfig --name {{eks_cluster_name}} --region {{region}}
  - name: Add helm repo
    shell: |
      helm repo remove {{reponame}}  
  - name: Uninstall  Chart
    shell: |
      helm   uninstall   {{chartname}}  
